# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-elasticache-cloudwatch-sns-alarms
  description: Terraform module that configures CloudWatch SNS alerts for ElastiCache
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-module, elasticbeanstalk, cloudwatch, sns, alarm, escalation, alert, notification, aws
